### ISSUE TITLE
Publish to Bower Registry

### ISSUE THREAD

**Issue by i-am-the-slime** [lumihq/purescript-react-basic-dom#15]
I'd like to publish a library that depends on this one (i-am-the-slime/purescript-react-testing-library#4). However, it looks like despite having a bower.json file it's not actually uploaded to the bower registry. Is this correct? I'm not an expert on this.

```
bower info --json purescript-react-basic-dom
[{
  "code": "ENOTFOUND",
  "id": "ENOTFOUND",
  "level": "error",
  "data": {},
  "message": "Package purescript-react-basic-dom not found",
  "stacktrace": "Error: Package purescript-react-basic-dom not found\n    at createError (/usr/local/lib/node_modules/bower/lib/util/createError.js:4:15)\n    at /usr/local/lib/node_modules/bower/lib/core/resolverFactory.js:243:23\n    at _fulfilled (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:854:54)\n    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:883:30\n    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:816:13)\n    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:624:44\n    at runSingle (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)\n    at flush (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:125:13)\n    at processTicksAndRejections (node:internal/process/task_queues:75:11)"
}]
```

**Comment by hdgarrood** [comment]
Yes, that's correct. The bower registry is no longer accepting uploads. As a stopgap we are using the `new-packages.json` file in the `purescript/registry` repo for storing the same information.
